CREATE TYPE roles AS ENUM ('user', 'admin');

CREATE TABLE IF NOT EXISTS "users"
(
    "id"         SERIAL PRIMARY KEY NOT NULL,
    "username"   varchar(100),
    "surname"    varchar(100),
    "birth_date" date,
    "phone"      varchar(20),
    "email"      varchar(100),
    "password"   varchar(30),
    "role"       roles
);

CREATE TABLE IF NOT EXISTS "restaurants"
(
    "id"       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "owner"    varchar(50),
    "name"     varchar(100),
    "employee" varchar(50),
    "menu"     varchar(100),
    "table"    integer
);